library Glimpse;

{$IFDEF WIN64}
{$E wlx64}
{$ELSE}
{$E wlx}
{$ENDIF}

uses
  Winapi.Windows,
  uTypes in '..\src\uTypes.pas',
  uStatusBarLayout in '..\src\uStatusBarLayout.pas',
  uDefaults in '..\src\uDefaults.pas',
  uWlxAPI in 'uWlxAPI.pas',
  uPluginExports in 'uPluginExports.pas',
  uSettingsInterfaces in '..\src\uSettingsInterfaces.pas',
  uSettings in '..\src\uSettings.pas',
  uSettingsToggleService in '..\src\uSettingsToggleService.pas',
  uFrameOffsets in '..\src\uFrameOffsets.pas',
  uFFmpegLocator in '..\src\uFFmpegLocator.pas',
  uFFmpegExe in '..\src\uFFmpegExe.pas',
  uFrameView in 'uFrameView.pas',
  uExtractionWorker in '..\src\uExtractionWorker.pas',
  uStatusBarHostBar in 'uStatusBarHostBar.pas',
  uKeyInterceptionSubclass in 'uKeyInterceptionSubclass.pas',
  uPluginForm in 'uPluginForm.pas',
  uPluginServices in 'uPluginServices.pas',
  uDebugLog in '..\src\shared\uDebugLog.pas',
  uCacheStorage in '..\src\infrastructure\uCacheStorage.pas',
  uLruEvictionPolicy in '..\src\infrastructure\uLruEvictionPolicy.pas',
  uCache in '..\src\uCache.pas',
  uCacheKey in '..\src\uCacheKey.pas',
  uProbeCache in '..\src\uProbeCache.pas',
  uEnableRules in 'uEnableRules.pas',
  uSettingsControlsBundles in 'uSettingsControlsBundles.pas',
  uSettingsDialogHelpers in '..\src\uSettingsDialogHelpers.pas',
  uSettingsPresenters in 'uSettingsPresenters.pas',
  uSettingsDlg in 'uSettingsDlg.pas',
  uCaptureShortcutDlg in 'uCaptureShortcutDlg.pas',
  uFrameFileNames in '..\src\uFrameFileNames.pas',
  uBitmapSaver in '..\src\uBitmapSaver.pas',
  uClipboardImage in '..\src\uClipboardImage.pas',
  uClipboardFileDrop in '..\src\uClipboardFileDrop.pas',
  uClipboardFormatStrategies in '..\src\uClipboardFormatStrategies.pas',
  uSettingsGroups in '..\src\uSettingsGroups.pas',
  uZoomController in 'uZoomController.pas',
  uViewModeLogic in 'uViewModeLogic.pas',
  uExtractionPlanner in '..\src\uExtractionPlanner.pas',
  uToolbarLayout in 'uToolbarLayout.pas',
  uToolbarGlyphLibrary in 'uToolbarGlyphLibrary.pas',
  uToolbarBuilder in 'uToolbarBuilder.pas',
  uToolbarController in 'uToolbarController.pas',
  uViewportRefreshDebouncer in 'uViewportRefreshDebouncer.pas',
  uLoadTimeRecorder in 'uLoadTimeRecorder.pas',
  uProgressIndicator in 'uProgressIndicator.pas',
  uFileNavigator in '..\src\uFileNavigator.pas',
  uPathExpand in '..\src\uPathExpand.pas',
  uColorConv in '..\src\uColorConv.pas',
  uRunProcess in '..\src\uRunProcess.pas',
  uFrameExtractor in '..\src\uFrameExtractor.pas',
  uViewModeLayout in 'uViewModeLayout.pas',
  uFrameExport in 'uFrameExport.pas',
  uSaveDialogPresenter in 'uSaveDialogPresenter.pas',
  uClipboardPublisher in 'uClipboardPublisher.pas',
  uFrameRenderPipeline in 'uFrameRenderPipeline.pas',
  uFrameDimensionPredictor in 'uFrameDimensionPredictor.pas',
  uExtractionController in 'uExtractionController.pas',
  uSaveResolutionExtractor in 'uSaveResolutionExtractor.pas',
  uBannerInfo in '..\src\uBannerInfo.pas',
  uBannerPainter in '..\src\uBannerPainter.pas',
  uCombinedGrid in '..\src\uCombinedGrid.pas',
  uTimecodeOverlay in '..\src\uTimecodeOverlay.pas',
  uFrameSelectionPolicy in '..\src\application\uFrameSelectionPolicy.pas',
  uCacheMaintenance in '..\src\application\uCacheMaintenance.pas',
  uVideoInfo in '..\src\uVideoInfo.pas',
  uLineSplitter in '..\src\infrastructure\uLineSplitter.pas',
  uFFmpegProbeParser in '..\src\infrastructure\uFFmpegProbeParser.pas',
  uFFmpegCmdLine in '..\src\infrastructure\uFFmpegCmdLine.pas',
  uIniEncoding in '..\src\infrastructure\uIniEncoding.pas',
  uIniDocument in '..\src\infrastructure\uIniDocument.pas',
  uRenderDefaults in '..\src\uRenderDefaults.pas',
  uPluginMessages in '..\src\shared\uPluginMessages.pas',
  uHotkeysVcl in 'uHotkeysVcl.pas',
  uPluginAppearance in 'uPluginAppearance.pas',
  uTextMeasurement in 'uTextMeasurement.pas',
  uFrameNotificationSink in '..\src\uFrameNotificationSink.pas',
  uPluginContext in 'uPluginContext.pas',
  uCommandDescriptors in 'uCommandDescriptors.pas',
  uPluginDllPin in 'uPluginDllPin.pas',
  uVideoProbing in '..\src\uVideoProbing.pas',
  uBitmapResize in '..\src\uBitmapResize.pas',
  uThumbnailRender in '..\src\uThumbnailRender.pas',
  uSettingsDlgLogic in '..\src\uSettingsDlgLogic.pas',
  uSettingsDlgUI in '..\src\uSettingsDlgUI.pas',
  uNoShadowHints in '..\src\uNoShadowHints.pas',
  uPlatformDetect in '..\src\uPlatformDetect.pas',
  uProgressModalForm in 'uProgressModalForm.pas',
  uBitmapWorkThread in 'uBitmapWorkThread.pas';

exports
  ListLoad,
  ListLoadW,
  ListLoadNext,
  ListLoadNextW,
  ListCloseWindow,
  ListGetDetectString,
  ListSearchText,
  ListSendCommand,
  ListSetDefaultParams,
  ListGetPreviewBitmap,
  ListGetPreviewBitmapW;

begin
  {Surface forgotten Free calls as a Delphi-builtin leak dialog when TC unloads
   the DLL. Debug-only: the report runs at finalization and would be noise for
   end users in release builds.}
  {$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
  {$ENDIF}
end.
