library Glimpse;

{$IFDEF WIN64}
{$E wlx64}
{$ELSE}
{$E wlx}
{$ENDIF}

uses
  Winapi.Windows,
  Types in '..\src\domain\Types.pas',
  StatusBarLayout in '..\src\domain\StatusBar\StatusBarLayout.pas',
  Defaults in '..\src\domain\Settings\Defaults.pas',
  WlxAPI in 'Core\WlxAPI.pas',
  PluginExports in 'Core\PluginExports.pas',
  IniStore in '..\src\domain\Settings\IniStore.pas',
  SettingsInterfaces in '..\src\domain\Settings\SettingsInterfaces.pas',
  Settings in '..\src\domain\Settings\Settings.pas',
  SettingsToggleService in '..\src\domain\Settings\SettingsToggleService.pas',
  FrameOffsets in '..\src\domain\Frame\FrameOffsets.pas',
  FFmpegLocator in '..\src\infrastructure\FFmpegLocator.pas',
  FFmpegExe in '..\src\infrastructure\FFmpegExe.pas',
  FrameView in 'Widgets\FrameView.pas',
  FrameCellStore in 'Widgets\FrameCellStore.pas',
  FrameGeometry in 'Widgets\FrameGeometry.pas',
  FrameViewRenderer in 'Widgets\FrameViewRenderer.pas',
  ExtractionWorker in '..\src\domain\Frame\ExtractionWorker.pas',
  StatusBarHostBar in 'Widgets\StatusBarHostBar.pas',
  KeyInterceptionSubclass in 'Hotkeys\KeyInterceptionSubclass.pas',
  PluginForm in 'Forms\PluginForm.pas',
  PluginServices in 'Core\PluginServices.pas',
  Logging in '..\src\shared\Logging.pas',
  CacheStorage in '..\src\infrastructure\CacheStorage.pas',
  LruEvictionPolicy in '..\src\infrastructure\LruEvictionPolicy.pas',
  Cache in '..\src\domain\Cache\Cache.pas',
  FrameCacheFactory in '..\src\infrastructure\FrameCacheFactory.pas',
  CacheKey in '..\src\domain\Cache\CacheKey.pas',
  ProbeCache in '..\src\domain\Cache\ProbeCache.pas',
  EnableRules in 'Commands\EnableRules.pas',
  SettingsControlsBundles in 'Presenters\SettingsControlsBundles.pas',
  SettingsDialogHelpers in '..\src\infrastructure\SettingsDialogHelpers.pas',
  SettingsPresenters in 'Presenters\SettingsPresenters.pas',
  SettingsDlg in 'Forms\SettingsDlg.pas',
  CaptureShortcutDlg in 'Forms\CaptureShortcutDlg.pas',
  FrameFileNames in '..\src\domain\Frame\FrameFileNames.pas',
  BitmapSaver in '..\src\domain\Render\BitmapSaver.pas',
  ClipboardImage in '..\src\application\ClipboardImage.pas',
  VclClipboard in '..\src\infrastructure\VclClipboard.pas',
  ClipboardFileDrop in '..\src\infrastructure\ClipboardFileDrop.pas',
  ClipboardFormatStrategies in '..\src\domain\Clipboard\ClipboardFormatStrategies.pas',
  SettingsGroups in '..\src\domain\Settings\SettingsGroups.pas',
  ZoomController in 'Controllers\ZoomController.pas',
  ViewModeLogic in 'ViewMode\ViewModeLogic.pas',
  ExtractionPlanner in '..\src\domain\Frame\ExtractionPlanner.pas',
  ToolbarLayout in 'Toolbar\ToolbarLayout.pas',
  ToolbarGlyphLibrary in 'Toolbar\ToolbarGlyphLibrary.pas',
  ToolbarBuilder in 'Toolbar\ToolbarBuilder.pas',
  ToolbarController in 'Controllers\ToolbarController.pas',
  ViewportRefreshDebouncer in 'Services\ViewportRefreshDebouncer.pas',
  LoadTimeRecorder in 'Services\LoadTimeRecorder.pas',
  ProgressIndicator in 'Widgets\ProgressIndicator.pas',
  ProgressReporter in 'Services\ProgressReporter.pas',
  FormProgressReporter in 'Presenters\FormProgressReporter.pas',
  OverrideFramesScope in 'Util\OverrideFramesScope.pas',
  FileNavigator in '..\src\infrastructure\FileNavigator.pas',
  PathExpand in '..\src\shared\PathExpand.pas',
  ColorConv in '..\src\domain\Render\ColorConv.pas',
  ProcessRunner in '..\src\infrastructure\ProcessRunner.pas',
  FrameExtractor in '..\src\domain\Frame\FrameExtractor.pas',
  ViewModeLayout in 'ViewMode\ViewModeLayout.pas',
  ExportTargetResolver in 'Services\ExportTargetResolver.pas',
  FrameExportTypes in 'Services\FrameExportTypes.pas',
  FrameSaver in 'Services\FrameSaver.pas',
  FrameExport in 'Services\FrameExport.pas',
  SaveDialogPresenter in 'Presenters\SaveDialogPresenter.pas',
  ClipboardPublisher in 'Services\ClipboardPublisher.pas',
  FrameRenderPipeline in 'Services\FrameRenderPipeline.pas',
  FrameDimensionPredictor in 'Services\FrameDimensionPredictor.pas',
  ExtractionController in 'Controllers\ExtractionController.pas',
  SaveResolutionExtractor in 'Services\SaveResolutionExtractor.pas',
  BannerInfo in '..\src\domain\Render\BannerInfo.pas',
  BannerPainter in '..\src\domain\Render\BannerPainter.pas',
  CombinedGrid in '..\src\domain\Render\CombinedGrid.pas',
  TimecodeOverlay in '..\src\domain\Render\TimecodeOverlay.pas',
  FrameSelectionPolicy in '..\src\application\FrameSelectionPolicy.pas',
  CacheMaintenance in '..\src\application\CacheMaintenance.pas',
  VideoInfo in '..\src\domain\Video\VideoInfo.pas',
  LineSplitter in '..\src\infrastructure\LineSplitter.pas',
  FFmpegProbeParser in '..\src\infrastructure\FFmpegProbeParser.pas',
  FFmpegCmdLine in '..\src\infrastructure\FFmpegCmdLine.pas',
  IniEncoding in '..\src\infrastructure\IniEncoding.pas',
  IniDocument in '..\src\infrastructure\IniDocument.pas',
  RenderDefaults in '..\src\domain\Render\RenderDefaults.pas',
  PluginMessages in '..\src\shared\PluginMessages.pas',
  HotkeysVcl in 'Hotkeys\HotkeysVcl.pas',
  PluginAppearance in 'Core\PluginAppearance.pas',
  TextMeasurement in 'Util\TextMeasurement.pas',
  FrameNotificationSink in '..\src\domain\Frame\FrameNotificationSink.pas',
  PluginContext in 'Core\PluginContext.pas',
  CommandDescriptors in 'Commands\CommandDescriptors.pas',
  PluginDllPin in 'Core\PluginDllPin.pas',
  VideoProbing in '..\src\domain\Video\VideoProbing.pas',
  BitmapResize in '..\src\domain\Render\BitmapResize.pas',
  ThumbnailRender in '..\src\application\ThumbnailRender.pas',
  SettingsDlgLogic in '..\src\application\SettingsDlgLogic.pas',
  SettingsDlgUI in '..\src\infrastructure\SettingsDlgUI.pas',
  NoShadowHints in '..\src\shared\NoShadowHints.pas',
  PlatformDetect in '..\src\shared\PlatformDetect.pas',
  ProgressModalForm in 'Forms\ProgressModalForm.pas',
  BitmapWorkThread in 'Services\BitmapWorkThread.pas';

exports
  ListLoad,
  ListLoadW,
  ListLoadNext,
  ListLoadNextW,
  ListCloseWindow,
  ListGetDetectString,
  ListSearchText,
  ListSendCommand,
  ListSetDefaultParams,
  ListGetPreviewBitmap,
  ListGetPreviewBitmapW;

begin
  {Surface forgotten Free calls as a leak dialog when TC unloads the DLL.
   Debug-only so release end users do not see the report.}
  {$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
  {$ENDIF}
end.
