program GlimpseTests;

{$STRONGLINKTYPES ON}
{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  DUnitX.TestFramework,
  DUnitX.Loggers.Console,
  DUnitX.Loggers.XML.NUnit,
  uTypes in '..\src\uTypes.pas',
  uStatusBarLayout in '..\src\uStatusBarLayout.pas',
  uDefaults in '..\src\uDefaults.pas',
  uSettingsGroups in '..\src\uSettingsGroups.pas',
  uSettings in '..\src\uSettings.pas',
  uSettingsToggleService in '..\src\uSettingsToggleService.pas',
  TestSettingsToggleService in 'TestSettingsToggleService.pas',
  uFrameOffsets in '..\src\uFrameOffsets.pas',
  uFFmpegLocator in '..\src\uFFmpegLocator.pas',
  uFFmpegExe in '..\src\uFFmpegExe.pas',
  TestFFmpegLocator in 'TestFFmpegLocator.pas',
  TestSettings in 'TestSettings.pas',
  uHotkeys in '..\src\uHotkeys.pas',
  uHotkeysCodec in '..\src\uHotkeysCodec.pas',
  uHotkeysDisplay in '..\src\uHotkeysDisplay.pas',
  TestHotkeys in 'TestHotkeys.pas',
  TestHotkeysCodec in 'TestHotkeysCodec.pas',
  TestHotkeysDisplay in 'TestHotkeysDisplay.pas',
  uCaptureShortcutDlg in '..\wlx\uCaptureShortcutDlg.pas',
  TestFrameOffsets in 'TestFrameOffsets.pas',
  TestFFmpegExe in 'TestFFmpegExe.pas',
  TestFFmpegProbeParser in 'TestFFmpegProbeParser.pas',
  TestFFmpegCmdLine in 'TestFFmpegCmdLine.pas',
  uFrameView in '..\wlx\uFrameView.pas',
  uExtractionWorker in '..\src\uExtractionWorker.pas',
  uStatusBarHostBar in '..\wlx\uStatusBarHostBar.pas',
  uKeyInterceptionSubclass in '..\wlx\uKeyInterceptionSubclass.pas',
  TestKeyInterceptionSubclass in 'TestKeyInterceptionSubclass.pas',
  uPluginForm in '..\wlx\uPluginForm.pas',
  uPluginServices in '..\wlx\uPluginServices.pas',
  TestPluginServices in 'TestPluginServices.pas',
  TestFrameView in 'TestFrameView.pas',
  uDebugLog in '..\src\shared\uDebugLog.pas',
  uCacheStorage in '..\src\infrastructure\uCacheStorage.pas',
  uLruEvictionPolicy in '..\src\infrastructure\uLruEvictionPolicy.pas',
  uCache in '..\src\uCache.pas',
  uCacheKey in '..\src\uCacheKey.pas',
  TestCacheKey in 'TestCacheKey.pas',
  TestCache in 'TestCache.pas',
  TestLruEvictionPolicy in 'TestLruEvictionPolicy.pas',
  uFrameFileNames in '..\src\uFrameFileNames.pas',
  TestFrameFileNames in 'TestFrameFileNames.pas',
  uBitmapSaver in '..\src\uBitmapSaver.pas',
  TestBitmapSaver in 'TestBitmapSaver.pas',
  uClipboardImage in '..\src\uClipboardImage.pas',
  TestClipboardImage in 'TestClipboardImage.pas',
  uClipboardFileDrop in '..\src\uClipboardFileDrop.pas',
  TestClipboardFileDrop in 'TestClipboardFileDrop.pas',
  uClipboardFormatStrategies in '..\src\uClipboardFormatStrategies.pas',
  TestClipboardFormatStrategies in 'TestClipboardFormatStrategies.pas',
  uZoomController in '..\wlx\uZoomController.pas',
  TestZoomController in 'TestZoomController.pas',
  uViewModeLogic in '..\wlx\uViewModeLogic.pas',
  TestViewModeLogic in 'TestViewModeLogic.pas',
  uExtractionPlanner in '..\src\uExtractionPlanner.pas',
  TestExtractionPlanner in 'TestExtractionPlanner.pas',
  uToolbarLayout in '..\wlx\uToolbarLayout.pas',
  TestToolbarLayout in 'TestToolbarLayout.pas',
  uToolbarGlyphLibrary in '..\wlx\uToolbarGlyphLibrary.pas',
  TestToolbarGlyphLibrary in 'TestToolbarGlyphLibrary.pas',
  uToolbarBuilder in '..\wlx\uToolbarBuilder.pas',
  uFileNavigator in '..\src\uFileNavigator.pas',
  TestFileNavigator in 'TestFileNavigator.pas',
  TestDebugLog in 'TestDebugLog.pas',
  uPathExpand in '..\src\uPathExpand.pas',
  TestPathExpand in 'TestPathExpand.pas',
  TestTypes in 'TestTypes.pas',
  uColorConv in '..\src\uColorConv.pas',
  TestColorConv in 'TestColorConv.pas',
  uRunProcess in '..\src\uRunProcess.pas',
  TestRunProcess in 'TestRunProcess.pas',
  uFrameExtractor in '..\src\uFrameExtractor.pas',
  TestFrameExtractor in 'TestFrameExtractor.pas',
  TestExtractionWorker in 'TestExtractionWorker.pas',
  uViewModeLayout in '..\wlx\uViewModeLayout.pas',
  TestViewModeLayout in 'TestViewModeLayout.pas',
  uFrameExport in '..\wlx\uFrameExport.pas',
  uSaveDialogPresenter in '..\wlx\uSaveDialogPresenter.pas',
  uClipboardPublisher in '..\wlx\uClipboardPublisher.pas',
  uFrameRenderPipeline in '..\wlx\uFrameRenderPipeline.pas',
  uFrameDimensionPredictor in '..\wlx\uFrameDimensionPredictor.pas',
  TestFrameExport in 'TestFrameExport.pas',
  uExtractionController in '..\wlx\uExtractionController.pas',
  TestExtractionController in 'TestExtractionController.pas',
  uSaveResolutionExtractor in '..\wlx\uSaveResolutionExtractor.pas',
  TestSaveResolutionExtractor in 'TestSaveResolutionExtractor.pas',
  uWcxAPI in '..\wcx\uWcxAPI.pas',
  uWcxSettings in '..\wcx\uWcxSettings.pas',
  TestWcxSettings in 'TestWcxSettings.pas',
  TestWcxAPI in 'TestWcxAPI.pas',
  uCmdLineTokens in '..\wcx\uCmdLineTokens.pas',
  TestCmdLineTokens in 'TestCmdLineTokens.pas',
  uWcxPresetValidation in '..\wcx\uWcxPresetValidation.pas',
  TestWcxPresetValidation in 'TestWcxPresetValidation.pas',
  uWcxPresetTemplate in '..\wcx\uWcxPresetTemplate.pas',
  TestWcxPresetTemplate in 'TestWcxPresetTemplate.pas',
  uFileNameDedupe in '..\wcx\uFileNameDedupe.pas',
  TestFileNameDedupe in 'TestFileNameDedupe.pas',
  uWcxPresets in '..\wcx\uWcxPresets.pas',
  TestWcxPresets in 'TestWcxPresets.pas',
  uWcxEntryExtractors in '..\wcx\uWcxEntryExtractors.pas',
  uWcxArchiveHandle in '..\wcx\uWcxArchiveHandle.pas',
  uWcxErrorMapping in '..\wcx\uWcxErrorMapping.pas',
  uWcxExtractionController in '..\wcx\uWcxExtractionController.pas',
  uWcxArchiveCoordinator in '..\wcx\uWcxArchiveCoordinator.pas',
  TestWcxArchiveCoordinator in 'TestWcxArchiveCoordinator.pas',
  uSettingsSaveOrchestrator in '..\wcx\uSettingsSaveOrchestrator.pas',
  TestSettingsSaveOrchestrator in 'TestSettingsSaveOrchestrator.pas',
  uWcxSettingsRepository in '..\wcx\uWcxSettingsRepository.pas',
  TestWcxSettingsRepository in 'TestWcxSettingsRepository.pas',
  uWcxPresetsRepository in '..\wcx\uWcxPresetsRepository.pas',
  TestWcxPresetsRepository in 'TestWcxPresetsRepository.pas',
  TestWcxArchiveHandle in 'TestWcxArchiveHandle.pas',
  uWcxListing in '..\wcx\uWcxListing.pas',
  TestWcxListing in 'TestWcxListing.pas',
  TestWcxEntryExtractors in 'TestWcxEntryExtractors.pas',
  uWcxProgressBridge in '..\wcx\uWcxProgressBridge.pas',
  TestWcxProgressBridge in 'TestWcxProgressBridge.pas',
  uWcxPresetExtractor in '..\wcx\uWcxPresetExtractor.pas',
  TestWcxPresetExtractor in 'TestWcxPresetExtractor.pas',
  uWcxPresetEditorModel in '..\wcx\uWcxPresetEditorModel.pas',
  TestWcxPresetEditorModel in 'TestWcxPresetEditorModel.pas',
  uUnicodeIniFile in '..\src\uUnicodeIniFile.pas',
  TestUnicodeIniFile in 'TestUnicodeIniFile.pas',
  uBannerInfo in '..\src\uBannerInfo.pas',
  uBannerPainter in '..\src\uBannerPainter.pas',
  uCombinedGrid in '..\src\uCombinedGrid.pas',
  uTimecodeOverlay in '..\src\uTimecodeOverlay.pas',
  uFrameSelectionPolicy in '..\src\application\uFrameSelectionPolicy.pas',
  TestFrameSelectionPolicy in 'TestFrameSelectionPolicy.pas',
  uCacheMaintenance in '..\src\application\uCacheMaintenance.pas',
  TestCacheMaintenance in 'TestCacheMaintenance.pas',
  uVideoInfo in '..\src\uVideoInfo.pas',
  TestVideoInfo in 'TestVideoInfo.pas',
  uLineSplitter in '..\src\infrastructure\uLineSplitter.pas',
  TestLineSplitter in 'TestLineSplitter.pas',
  uFFmpegProbeParser in '..\src\infrastructure\uFFmpegProbeParser.pas',
  uFFmpegCmdLine in '..\src\infrastructure\uFFmpegCmdLine.pas',
  uIniEncoding in '..\src\infrastructure\uIniEncoding.pas',
  uIniDocument in '..\src\infrastructure\uIniDocument.pas',
  uRenderDefaults in '..\src\uRenderDefaults.pas',
  uPluginMessages in '..\src\shared\uPluginMessages.pas',
  uHotkeysVcl in '..\wlx\uHotkeysVcl.pas',
  TestHotkeysVcl in 'TestHotkeysVcl.pas',
  uTextMeasurement in '..\wlx\uTextMeasurement.pas',
  uFrameNotificationSink in '..\src\uFrameNotificationSink.pas',
  uPluginContext in '..\wlx\uPluginContext.pas',
  TestPluginContext in 'TestPluginContext.pas',
  uCommandDescriptors in '..\wlx\uCommandDescriptors.pas',
  TestCommandDescriptors in 'TestCommandDescriptors.pas',
  uPluginDllPin in '..\wlx\uPluginDllPin.pas',
  uVideoProbing in '..\src\uVideoProbing.pas',
  uWcxFrameCache in '..\wcx\uWcxFrameCache.pas',
  uPresetExtractReporter in '..\wcx\uPresetExtractReporter.pas',
  TestPresetExtractReporter in 'TestPresetExtractReporter.pas',
  uWcxProgressCallback in '..\wcx\uWcxProgressCallback.pas',
  TestWcxProgressCallback in 'TestWcxProgressCallback.pas',
  TestBannerInfo in 'TestBannerInfo.pas',
  TestBannerPainter in 'TestBannerPainter.pas',
  TestCombinedGrid in 'TestCombinedGrid.pas',
  TestTimecodeOverlay in 'TestTimecodeOverlay.pas',
  uProbeCache in '..\src\uProbeCache.pas',
  TestProbeCache in 'TestProbeCache.pas',
  uBitmapResize in '..\src\uBitmapResize.pas',
  TestBitmapResize in 'TestBitmapResize.pas',
  uThumbnailRender in '..\src\uThumbnailRender.pas',
  TestThumbnailRender in 'TestThumbnailRender.pas',
  uSettingsDlgLogic in '..\src\uSettingsDlgLogic.pas',
  uSettingsDlgUI in '..\src\uSettingsDlgUI.pas',
  TestSettingsDlgUI in 'TestSettingsDlgUI.pas',
  TestSettingsGroups in 'TestSettingsGroups.pas',
  TestSettingsDlgLogic in 'TestSettingsDlgLogic.pas',
  uEnableRules in '..\wlx\uEnableRules.pas',
  TestEnableRules in 'TestEnableRules.pas',
  uSettingsControlsBundles in '..\wlx\uSettingsControlsBundles.pas',
  TestSettingsControlsBundles in 'TestSettingsControlsBundles.pas',
  uSettingsDialogHelpers in '..\src\uSettingsDialogHelpers.pas',
  TestSettingsDialogHelpers in 'TestSettingsDialogHelpers.pas',
  uSettingsPresenters in '..\wlx\uSettingsPresenters.pas',
  TestSettingsPresenters in 'TestSettingsPresenters.pas',
  uWcxSettingsControlsBundles in '..\wcx\uWcxSettingsControlsBundles.pas',
  TestWcxSettingsControlsBundles in 'TestWcxSettingsControlsBundles.pas',
  uWcxSettingsPresenters in '..\wcx\uWcxSettingsPresenters.pas',
  TestWcxSettingsPresenters in 'TestWcxSettingsPresenters.pas',
  uStatusBarTokens in '..\src\uStatusBarTokens.pas',
  uStatusBarTemplate in '..\src\uStatusBarTemplate.pas',
  uStatusBarFormatters in '..\src\uStatusBarFormatters.pas',
  uStatusBarRenderer in '..\wlx\uStatusBarRenderer.pas',
  TestStatusBarTokens in 'TestStatusBarTokens.pas',
  TestStatusBarTemplate in 'TestStatusBarTemplate.pas',
  TestStatusBarFormatters in 'TestStatusBarFormatters.pas',
  TestStatusBarRenderer in 'TestStatusBarRenderer.pas',
  TestPlatformDetect in 'TestPlatformDetect.pas',
  uProgressModalForm in '..\wlx\uProgressModalForm.pas',
  uBitmapWorkThread in '..\wlx\uBitmapWorkThread.pas',
  TestBitmapWorkThread in 'TestBitmapWorkThread.pas';

var
  Runner: ITestRunner;
  Results: IRunResults;
  Logger: ITestLogger;
  NUnitLogger: ITestLogger;
begin
  ReportMemoryLeaksOnShutdown := True;
  try
    TDUnitX.CheckCommandLine;
    Runner := TDUnitX.CreateRunner;
    Runner.UseRTTI := True;
    Logger := TDUnitXConsoleLogger.Create(True);
    Runner.AddLogger(Logger);
    if TDUnitX.Options.XMLOutputFile <> '' then
    begin
      NUnitLogger := TDUnitXXMLNUnitFileLogger.Create(TDUnitX.Options.XMLOutputFile);
      Runner.AddLogger(NUnitLogger);
    end;
    Runner.FailsOnNoAsserts := False;
    Results := Runner.Execute;
    if not Results.AllPassed then
      System.ExitCode := EXIT_ERRORS;
    {$IFNDEF CI}
    if TDUnitX.Options.ExitBehavior = TDUnitXExitBehavior.Pause then
    begin
      System.Write('Done.. press <Enter> key to quit.');
      System.Readln;
    end;
    {$ENDIF}
  except
    on E: Exception do
      System.Writeln(E.ClassName, ': ', E.Message);
  end;
end.
