program GlimpseTests;

{$STRONGLINKTYPES ON}
{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  DUnitX.TestFramework,
  DUnitX.Loggers.Console,
  DUnitX.Loggers.XML.NUnit,
  Types in '..\src\domain\Types.pas',
  StatusBarLayout in '..\src\domain\StatusBar\StatusBarLayout.pas',
  Defaults in '..\src\domain\Settings\Defaults.pas',
  SettingsGroups in '..\src\domain\Settings\SettingsGroups.pas',
  SettingsInterfaces in '..\src\domain\Settings\SettingsInterfaces.pas',
  TestSettingsInterfaces in 'TestSettingsInterfaces.pas',
  Settings in '..\src\domain\Settings\Settings.pas',
  SettingsToggleService in '..\src\domain\Settings\SettingsToggleService.pas',
  TestSettingsToggleService in 'TestSettingsToggleService.pas',
  FrameOffsets in '..\src\domain\Frame\FrameOffsets.pas',
  FFmpegLocator in '..\src\domain\Frame\FFmpegLocator.pas',
  FFmpegExe in '..\src\infrastructure\FFmpegExe.pas',
  TestFFmpegLocator in 'TestFFmpegLocator.pas',
  TestSettings in 'TestSettings.pas',
  Hotkeys in '..\src\domain\Hotkeys\Hotkeys.pas',
  HotkeysCodec in '..\src\domain\Hotkeys\HotkeysCodec.pas',
  HotkeysDisplay in '..\src\domain\Hotkeys\HotkeysDisplay.pas',
  TestHotkeys in 'TestHotkeys.pas',
  TestHotkeysCodec in 'TestHotkeysCodec.pas',
  TestHotkeysDisplay in 'TestHotkeysDisplay.pas',
  CaptureShortcutDlg in '..\wlx\Forms\CaptureShortcutDlg.pas',
  TestFrameOffsets in 'TestFrameOffsets.pas',
  TestFFmpegExe in 'TestFFmpegExe.pas',
  TestFFmpegProbeParser in 'TestFFmpegProbeParser.pas',
  TestFFmpegCmdLine in 'TestFFmpegCmdLine.pas',
  FrameView in '..\wlx\Widgets\FrameView.pas',
  ExtractionWorker in '..\src\domain\Frame\ExtractionWorker.pas',
  StatusBarHostBar in '..\wlx\Widgets\StatusBarHostBar.pas',
  KeyInterceptionSubclass in '..\wlx\Hotkeys\KeyInterceptionSubclass.pas',
  TestKeyInterceptionSubclass in 'TestKeyInterceptionSubclass.pas',
  PluginForm in '..\wlx\Forms\PluginForm.pas',
  PluginServices in '..\wlx\Core\PluginServices.pas',
  TestPluginServices in 'TestPluginServices.pas',
  TestFrameView in 'TestFrameView.pas',
  Logging in '..\src\shared\Logging.pas',
  CacheStorage in '..\src\infrastructure\CacheStorage.pas',
  LruEvictionPolicy in '..\src\infrastructure\LruEvictionPolicy.pas',
  Cache in '..\src\domain\Cache\Cache.pas',
  CacheKey in '..\src\domain\Cache\CacheKey.pas',
  TestCacheKey in 'TestCacheKey.pas',
  TestCache in 'TestCache.pas',
  TestLruEvictionPolicy in 'TestLruEvictionPolicy.pas',
  FrameFileNames in '..\src\domain\Frame\FrameFileNames.pas',
  TestFrameFileNames in 'TestFrameFileNames.pas',
  BitmapSaver in '..\src\domain\Render\BitmapSaver.pas',
  TestBitmapSaver in 'TestBitmapSaver.pas',
  ClipboardImage in '..\src\domain\Clipboard\ClipboardImage.pas',
  TestClipboardImage in 'TestClipboardImage.pas',
  ClipboardFileDrop in '..\src\domain\Clipboard\ClipboardFileDrop.pas',
  TestClipboardFileDrop in 'TestClipboardFileDrop.pas',
  ClipboardFormatStrategies in '..\src\domain\Clipboard\ClipboardFormatStrategies.pas',
  TestClipboardFormatStrategies in 'TestClipboardFormatStrategies.pas',
  ZoomController in '..\wlx\Controllers\ZoomController.pas',
  TestZoomController in 'TestZoomController.pas',
  ViewModeLogic in '..\wlx\ViewMode\ViewModeLogic.pas',
  TestViewModeLogic in 'TestViewModeLogic.pas',
  ExtractionPlanner in '..\src\domain\Frame\ExtractionPlanner.pas',
  TestExtractionPlanner in 'TestExtractionPlanner.pas',
  ToolbarLayout in '..\wlx\Toolbar\ToolbarLayout.pas',
  TestToolbarLayout in 'TestToolbarLayout.pas',
  ToolbarGlyphLibrary in '..\wlx\Toolbar\ToolbarGlyphLibrary.pas',
  TestToolbarGlyphLibrary in 'TestToolbarGlyphLibrary.pas',
  ToolbarBuilder in '..\wlx\Toolbar\ToolbarBuilder.pas',
  ViewportRefreshDebouncer in '..\wlx\Services\ViewportRefreshDebouncer.pas',
  TestViewportRefreshDebouncer in 'TestViewportRefreshDebouncer.pas',
  LoadTimeRecorder in '..\wlx\Services\LoadTimeRecorder.pas',
  TestLoadTimeRecorder in 'TestLoadTimeRecorder.pas',
  FileNavigator in '..\src\infrastructure\FileNavigator.pas',
  TestFileNavigator in 'TestFileNavigator.pas',
  TestDebugLog in 'TestDebugLog.pas',
  PathExpand in '..\src\shared\PathExpand.pas',
  TestPathExpand in 'TestPathExpand.pas',
  TestTypes in 'TestTypes.pas',
  ColorConv in '..\src\domain\Render\ColorConv.pas',
  TestColorConv in 'TestColorConv.pas',
  ProcessRunner in '..\src\infrastructure\ProcessRunner.pas',
  TestRunProcess in 'TestRunProcess.pas',
  FrameExtractor in '..\src\domain\Frame\FrameExtractor.pas',
  TestFrameExtractor in 'TestFrameExtractor.pas',
  TestExtractionWorker in 'TestExtractionWorker.pas',
  ViewModeLayout in '..\wlx\ViewMode\ViewModeLayout.pas',
  TestViewModeLayout in 'TestViewModeLayout.pas',
  FrameExport in '..\wlx\Services\FrameExport.pas',
  SaveDialogPresenter in '..\wlx\Presenters\SaveDialogPresenter.pas',
  ClipboardPublisher in '..\wlx\Services\ClipboardPublisher.pas',
  FrameRenderPipeline in '..\wlx\Services\FrameRenderPipeline.pas',
  FrameDimensionPredictor in '..\wlx\Services\FrameDimensionPredictor.pas',
  TestFrameExport in 'TestFrameExport.pas',
  ExtractionController in '..\wlx\Controllers\ExtractionController.pas',
  TestExtractionController in 'TestExtractionController.pas',
  ProgressReporter in '..\wlx\Services\ProgressReporter.pas',
  SaveResolutionExtractor in '..\wlx\Services\SaveResolutionExtractor.pas',
  TestSaveResolutionExtractor in 'TestSaveResolutionExtractor.pas',
  WcxAPI in '..\wcx\Core\WcxAPI.pas',
  WcxSettings in '..\wcx\Settings\WcxSettings.pas',
  TestWcxSettings in 'TestWcxSettings.pas',
  TestWcxAPI in 'TestWcxAPI.pas',
  CmdLineTokens in '..\wcx\Util\CmdLineTokens.pas',
  TestCmdLineTokens in 'TestCmdLineTokens.pas',
  WcxPresetValidation in '..\wcx\Entries\WcxPresetValidation.pas',
  TestWcxPresetValidation in 'TestWcxPresetValidation.pas',
  WcxPresetTemplate in '..\wcx\Entries\WcxPresetTemplate.pas',
  TestWcxPresetTemplate in 'TestWcxPresetTemplate.pas',
  FileNameDedupe in '..\wcx\Util\FileNameDedupe.pas',
  TestFileNameDedupe in 'TestFileNameDedupe.pas',
  WcxPresets in '..\wcx\Entries\WcxPresets.pas',
  TestWcxPresets in 'TestWcxPresets.pas',
  WcxEntryExtractors in '..\wcx\Entries\WcxEntryExtractors.pas',
  WcxArchiveHandle in '..\wcx\Core\WcxArchiveHandle.pas',
  WcxErrorMapping in '..\wcx\Util\WcxErrorMapping.pas',
  WcxExtractionController in '..\wcx\Services\WcxExtractionController.pas',
  WcxArchiveCoordinator in '..\wcx\Core\WcxArchiveCoordinator.pas',
  TestWcxArchiveCoordinator in 'TestWcxArchiveCoordinator.pas',
  SettingsSaveOrchestrator in '..\wcx\Services\SettingsSaveOrchestrator.pas',
  TestSettingsSaveOrchestrator in 'TestSettingsSaveOrchestrator.pas',
  WcxSettingsRepository in '..\wcx\Settings\WcxSettingsRepository.pas',
  TestWcxSettingsRepository in 'TestWcxSettingsRepository.pas',
  WcxPresetsRepository in '..\wcx\Entries\WcxPresetsRepository.pas',
  TestWcxPresetsRepository in 'TestWcxPresetsRepository.pas',
  TestWcxArchiveHandle in 'TestWcxArchiveHandle.pas',
  WcxListing in '..\wcx\Services\WcxListing.pas',
  TestWcxListing in 'TestWcxListing.pas',
  TestWcxEntryExtractors in 'TestWcxEntryExtractors.pas',
  WcxProgressBridge in '..\wcx\Services\WcxProgressBridge.pas',
  TestWcxProgressBridge in 'TestWcxProgressBridge.pas',
  WcxPresetExtractor in '..\wcx\Entries\WcxPresetExtractor.pas',
  TestWcxPresetExtractor in 'TestWcxPresetExtractor.pas',
  WcxPresetEditorModel in '..\wcx\Entries\WcxPresetEditorModel.pas',
  TestWcxPresetEditorModel in 'TestWcxPresetEditorModel.pas',
  UnicodeIniFile in '..\src\infrastructure\UnicodeIniFile.pas',
  TestUnicodeIniFile in 'TestUnicodeIniFile.pas',
  BannerInfo in '..\src\domain\Render\BannerInfo.pas',
  BannerPainter in '..\src\domain\Render\BannerPainter.pas',
  CombinedGrid in '..\src\domain\Render\CombinedGrid.pas',
  TimecodeOverlay in '..\src\domain\Render\TimecodeOverlay.pas',
  FrameSelectionPolicy in '..\src\application\FrameSelectionPolicy.pas',
  TestFrameSelectionPolicy in 'TestFrameSelectionPolicy.pas',
  CacheMaintenance in '..\src\application\CacheMaintenance.pas',
  TestCacheMaintenance in 'TestCacheMaintenance.pas',
  VideoInfo in '..\src\domain\Video\VideoInfo.pas',
  TestVideoInfo in 'TestVideoInfo.pas',
  LineSplitter in '..\src\infrastructure\LineSplitter.pas',
  TestLineSplitter in 'TestLineSplitter.pas',
  FFmpegProbeParser in '..\src\infrastructure\FFmpegProbeParser.pas',
  FFmpegCmdLine in '..\src\infrastructure\FFmpegCmdLine.pas',
  IniEncoding in '..\src\infrastructure\IniEncoding.pas',
  IniDocument in '..\src\infrastructure\IniDocument.pas',
  RenderDefaults in '..\src\domain\Render\RenderDefaults.pas',
  PluginMessages in '..\src\shared\PluginMessages.pas',
  HotkeysVcl in '..\wlx\Hotkeys\HotkeysVcl.pas',
  TestHotkeysVcl in 'TestHotkeysVcl.pas',
  TextMeasurement in '..\wlx\Util\TextMeasurement.pas',
  FrameNotificationSink in '..\src\domain\Frame\FrameNotificationSink.pas',
  PluginContext in '..\wlx\Core\PluginContext.pas',
  TestPluginContext in 'TestPluginContext.pas',
  CommandDescriptors in '..\wlx\Commands\CommandDescriptors.pas',
  TestCommandDescriptors in 'TestCommandDescriptors.pas',
  PluginDllPin in '..\wlx\Core\PluginDllPin.pas',
  VideoProbing in '..\src\domain\Video\VideoProbing.pas',
  WcxFrameCache in '..\wcx\Services\WcxFrameCache.pas',
  PresetExtractReporter in '..\wcx\Services\PresetExtractReporter.pas',
  TestPresetExtractReporter in 'TestPresetExtractReporter.pas',
  WcxProgressCallback in '..\wcx\Services\WcxProgressCallback.pas',
  TestWcxProgressCallback in 'TestWcxProgressCallback.pas',
  TestBannerInfo in 'TestBannerInfo.pas',
  TestBannerPainter in 'TestBannerPainter.pas',
  TestCombinedGrid in 'TestCombinedGrid.pas',
  TestTimecodeOverlay in 'TestTimecodeOverlay.pas',
  ProbeCache in '..\src\domain\Cache\ProbeCache.pas',
  TestProbeCache in 'TestProbeCache.pas',
  BitmapResize in '..\src\domain\Render\BitmapResize.pas',
  TestBitmapResize in 'TestBitmapResize.pas',
  ThumbnailRender in '..\src\domain\Render\ThumbnailRender.pas',
  TestThumbnailRender in 'TestThumbnailRender.pas',
  SettingsDlgLogic in '..\src\application\SettingsDlgLogic.pas',
  SettingsDlgUI in '..\src\application\SettingsDlgUI.pas',
  TestSettingsDlgUI in 'TestSettingsDlgUI.pas',
  TestSettingsGroups in 'TestSettingsGroups.pas',
  TestSettingsDlgLogic in 'TestSettingsDlgLogic.pas',
  EnableRules in '..\wlx\Commands\EnableRules.pas',
  TestEnableRules in 'TestEnableRules.pas',
  SettingsControlsBundles in '..\wlx\Presenters\SettingsControlsBundles.pas',
  TestSettingsControlsBundles in 'TestSettingsControlsBundles.pas',
  SettingsDialogHelpers in '..\src\application\SettingsDialogHelpers.pas',
  TestSettingsDialogHelpers in 'TestSettingsDialogHelpers.pas',
  SettingsPresenters in '..\wlx\Presenters\SettingsPresenters.pas',
  TestSettingsPresenters in 'TestSettingsPresenters.pas',
  WcxSettingsControlsBundles in '..\wcx\Presenters\WcxSettingsControlsBundles.pas',
  TestWcxSettingsControlsBundles in 'TestWcxSettingsControlsBundles.pas',
  WcxSettingsPresenters in '..\wcx\Presenters\WcxSettingsPresenters.pas',
  TestWcxSettingsPresenters in 'TestWcxSettingsPresenters.pas',
  StatusBarTokens in '..\src\domain\StatusBar\StatusBarTokens.pas',
  StatusBarTemplate in '..\src\domain\StatusBar\StatusBarTemplate.pas',
  StatusBarFormatters in '..\src\domain\StatusBar\StatusBarFormatters.pas',
  StatusBarRenderer in '..\wlx\Widgets\StatusBarRenderer.pas',
  TestStatusBarTokens in 'TestStatusBarTokens.pas',
  TestStatusBarTemplate in 'TestStatusBarTemplate.pas',
  TestStatusBarFormatters in 'TestStatusBarFormatters.pas',
  TestStatusBarRenderer in 'TestStatusBarRenderer.pas',
  TestPlatformDetect in 'TestPlatformDetect.pas',
  ProgressModalForm in '..\wlx\Forms\ProgressModalForm.pas',
  BitmapWorkThread in '..\wlx\Services\BitmapWorkThread.pas',
  TestBitmapWorkThread in 'TestBitmapWorkThread.pas',
  TestClipboardPublisher in 'wlx\Services\TestClipboardPublisher.pas',
  TestWcxFrameCache in 'wcx\Services\TestWcxFrameCache.pas',
  TestWcxExtractionController in 'wcx\Services\TestWcxExtractionController.pas';

var
  Runner: ITestRunner;
  Results: IRunResults;
  Logger: ITestLogger;
  NUnitLogger: ITestLogger;
begin
  ReportMemoryLeaksOnShutdown := True;
  try
    TDUnitX.CheckCommandLine;
    Runner := TDUnitX.CreateRunner;
    Runner.UseRTTI := True;
    Logger := TDUnitXConsoleLogger.Create(True);
    Runner.AddLogger(Logger);
    if TDUnitX.Options.XMLOutputFile <> '' then
    begin
      NUnitLogger := TDUnitXXMLNUnitFileLogger.Create(TDUnitX.Options.XMLOutputFile);
      Runner.AddLogger(NUnitLogger);
    end;
    Runner.FailsOnNoAsserts := False;
    Results := Runner.Execute;
    if not Results.AllPassed then
      System.ExitCode := EXIT_ERRORS;
    {$IFNDEF CI}
    if TDUnitX.Options.ExitBehavior = TDUnitXExitBehavior.Pause then
    begin
      System.Write('Done.. press <Enter> key to quit.');
      System.Readln;
    end;
    {$ENDIF}
  except
    on E: Exception do
      System.Writeln(E.ClassName, ': ', E.Message);
  end;
end.
